name = 'Blood on the River'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'ship'
    graphic = 'samuel'
    hitbox = [16, 16]
